# docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: "3.9"
services:
  web:
    build: .
    ports:
      - 80:80
    environment:
      PRODUCTION: 'true'

  cache:
    environment:
      TTL: '500'