# docker compose up -d

version: "3.9"
services:
  web:
    build: .
    volumes:
      - '.:/code'
    ports:
      - 8883:80
    environment:
      DEBUG: 'true'

  db:
    command: '-d'
    ports:
      - 5432:5432

  cache:
    ports:
      - 6379:6379